<a href="https://colab.research.google.com/github/pratham-239/UCS420/blob/main/Cognitive_Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print("Original Array:", a)
print("After adding 2:", a + 2)
print("After multiplying by 3:", a * 3)
print("After dividing by 2:", a / 2)

Original Array: [1 2 3 4 5]
After adding 2: [3 4 5 6 7]
After multiplying by 3: [ 3  6  9 12 15]
After dividing by 2: [0.5 1.  1.5 2.  2.5]


Q2

In [4]:
# arr = np.array([1, 2, 3, 6, 4, 5])
# print(arr[::-1])

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

unique, count = np.unique(x, return_counts=True)
most = unique[np.argmax(count)]
print("Most frequent value:", most)
print("Indices:", np.where(x == most)[0])

unique, count = np.unique(y, return_counts=True)
most = unique[np.argmax(count)]
print("Most frequent value:", most)
print("Indices:", np.where(y == most)[0])

Most frequent value: 1
Indices: [0 5 7 8 9]
Most frequent value: 1
Indices: [0 1 2]


Q3

In [5]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print(arr[0, 1])
print(arr[2, 0])

20
70


Q4

In [6]:
pratham = np.linspace(10, 100, 25)
print("Array:", pratham)
print("Dimensions:", pratham.ndim)
print("Shape:", pratham.shape)
print("Total elements:", pratham.size)
print("Data type:", pratham.dtype)
print("Total bytes:", pratham.nbytes)
transpose = pratham.reshape(25, 1)
print("Transpose using reshape:")
print(transpose)
print("Transpose using T:")
print(pratham.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5

In [7]:
ucs420_pratham = np.array([[10, 20, 30, 40],
                           [50, 60, 70, 80],
                           [90, 15, 20, 35]])
print("Array:")
print(ucs420_pratham)
print("Mean:", np.mean(ucs420_pratham))
print("Median:", np.median(ucs420_pratham))
print("Maximum:", np.max(ucs420_pratham))
print("Minimum:", np.min(ucs420_pratham))
print("Unique Elements:", np.unique(ucs420_pratham))
reshaped_ucs420_pratham = ucs420_pratham.reshape(4, 3)
print("Reshaped Array:")
print(reshaped_ucs420_pratham)
resized_ucs420_pratham = np.resize(ucs420_pratham, (2, 3))
print("Resized Array:")
print(resized_ucs420_pratham)

Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array:
[[10 20 30]
 [40 50 60]]
